#!/usr/bin/env node
// Generate idempotent seed SQL for the Supabase schema from the repo data.
//
//   node db/seed.mjs > db/seed.sql        # then run it in Supabase (SQL editor
//                                          #  or: supabase db execute -f db/seed.sql)
//
// Loads the taxonomy (topics + dependencies) and any reviewed-gated content
// files into the reference/content tables. Uses ON CONFLICT so it's safe to
// re-run. Everything here is global/read-only reference data — no child PII.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const dir = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(dir, '..');
const read = (p) => JSON.parse(fs.readFileSync(path.join(root, p), 'utf8'));

const topics = read('data/topics.json').topics;
const deps = read('data/dependencies.json').dependencies;

// SQL literal helpers.
const q = (s) => (s === null || s === undefined ? 'null' : `'${String(s).replace(/'/g, "''")}'`);
const jsonb = (v) => `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`;
const textArr = (a) => (a && a.length ? `ARRAY[${a.map(q).join(',')}]::text[]` : `'{}'::text[]`);
const numOrNull = (n) => (typeof n === 'number' ? n : 'null');

const out = [];
out.push('-- Generated by db/seed.mjs — idempotent. Global reference + reviewed content.');
out.push('begin;');

// --- topics ---------------------------------------------------------------
out.push('\n-- topics');
for (const t of topics) {
  out.push(
    `insert into public.topics (id,subject,domain,name,description,type,age_range_start,age_range_end,centrality,evidence,standards) values (`
    + `${q(t.id)},${q(t.subject)},${q(t.domain)},${q(t.name)},${q(t.description)},${q(t.type)},`
    + `${numOrNull(t.ageRangeStart)},${numOrNull(t.ageRangeEnd)},${numOrNull(t.centrality)},`
    + `${jsonb(t.evidence || [])},${textArr(t.standards)}) on conflict (id) do nothing;`,
  );
}

// --- dependencies (only hard/soft between known topics) -------------------
out.push('\n-- dependencies');
const ids = new Set(topics.map((t) => t.id));
for (const d of deps) {
  if (!ids.has(d.topicId) || !ids.has(d.prerequisiteId)) continue;
  out.push(
    `insert into public.dependencies (topic_id,prerequisite_id,strength,reason) values (`
    + `${q(d.topicId)},${q(d.prerequisiteId)},${q(d.strength)},${q(d.reason)}) `
    + `on conflict (topic_id,prerequisite_id) do nothing;`,
  );
}

// --- content_items (from content/*.json; reviewed flag preserved) ---------
out.push('\n-- content_items');
const contentDir = path.join(root, 'content');
let nContent = 0;
for (const f of fs.readdirSync(contentDir)) {
  if (!f.endsWith('.json')) continue;
  const c = JSON.parse(fs.readFileSync(path.join(contentDir, f), 'utf8'));
  if (!c.topicId) continue;
  const lane = c.subject === 'Mathematics' || c.subject === 'English' ? 'skill' : 'knowledge';
  out.push(
    `insert into public.content_items (topic_id,lane,age_min,age_max,standards,body,provenance,reviewed,version) values (`
    + `${q(c.topicId)},${q(lane)},${numOrNull(c.ageRange?.[0])},${numOrNull(c.ageRange?.[1])},`
    + `${textArr(c.standards)},${jsonb(c)},${jsonb(c.provenance || {})},${c.provenance?.reviewed ? 'true' : 'false'},1) `
    + `on conflict (topic_id,version) do nothing;`,
  );
  nContent++;
}

out.push('\ncommit;');
out.push(`-- seeded: ${topics.length} topics, ${deps.length} dependencies, ${nContent} content items`);

process.stdout.write(out.join('\n') + '\n');
process.stderr.write(`seed.sql: ${topics.length} topics, ${deps.length} deps, ${nContent} content\n`);
